# backend type
type = "libconfd-backend-etcdv3"

# backend address
host = [
	"127.0.0.1:2379",
]

# user name/password
user = "root"
password = "123456"
# public/private key
client-ca-keys = ""
client-cert = ""
client-key = ""
