app:
  name: nap-agent
logging:
  level: 5  #0 panic 0 fatal 1 error 2 warn 3 info 4 debug 5 trace 6
  report-caller: false
etcd:
  # backend address
  endpoints:
    - "127.0.0.1:2379"
  # user name/password
  user: ""
  password: ""
  # public/private key
  client-ca-keys: ""
  client-cert: ""
  client-key: ""
confd:
  confdir: "./../testdata/agent"
  interval: 10
  # Enable noop mode. Process all template resources; skip target update.
  noop: false
  # The string to prefix to keys. ("/")
  prefix: "/pgxs/nap/"
  # sync without check_cmd and reload_cmd.
  sync-only: false
  # run once and exit
  onetime: false
  # enable watch support
  watch: true
  # keep staged files
  keep-stage-file: false
  # PGP secret keyring (for use with crypt functions)
  pgp-private-key:  ""
